### ISSUE TITLE
Error after upgrading to Home Assistant 2022.7.1

### ISSUE THREAD

**Issue by acurrington** [snikch/climate.escea#13]
Have just updated my Home Assistant install to 2022.7.1, and now see this message in the log area

```
Platform error: climate

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config.py", line 877, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/lib/python3.10/site-packages/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/escea/climate.py", line 3, in <module>
    import escea
ModuleNotFoundError: No module named 'escea'
```

my configuration.yaml file has

```
climate:
 - platform: escea

```

Any ideas how to resolve?

**Comment by revilo951** [comment]
I have exactly the same issue

**Comment by snikch** [comment]
Anyone manage to sort this? If not I can have a look when I find some time.

**Comment by revilo951** [comment]
> Anyone manage to sort this? If not I can have a look when I find some time.

I've been poking around, had no luck yet. I know a little python, but this one is beyond me. If you can have a look that'd be awesome.

Also, thanks for a great plugin!

**Comment by khcnz** [comment]
I didn't seem to have this problem on 2022.7.x and I don't have it on 2022.8.x - I've got HA installed using the "Home Assistant Operating System" method

How do you have homeassistant installed? There was a python update in 2022.7 that maybe is related https://www.home-assistant.io/blog/2022/07/06/release-20227/

**Comment by ICULikeMac** [comment]
Has anyone got any updates on this? Will updating HA break this integration?

**Comment by SgtBatten** [comment]
Since September there has been an escea component in Home assistant Core.

**Comment by revilo951** [comment]
> Since September there has been an escea integration in Home assistant Core. I'd suggest you use that instead simply because it's part of core and not a custom integration any more. It was not long after we got this one into HACS that someone else got it into core.

That's awesome! Have you got a link to some details? I'm struggling to find out how to set it up using the core integration.

**Comment by SgtBatten** [comment]
https://www.home-assistant.io/integrations/escea/

There's not much to it. Remove the hacs integration and remove the climate entry in configuration.yaml for escea. Probably restart HA then add integration in settings>Devices and Services> integrations

**Comment by clowgg** [comment]
If youve have the previous custom integration installed then you don't seem to be able to install the new Core one. I get a pop up message when I try that says: "This device cannot be added from the UI. You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."

I haven't been able to find a way around this yet...  
Any ideas anyone?
